services:
  - type: web
    name: butterfly-demo
    env: python
    plan: free
    buildCommand: python3 -m pip install -r requirements.txt
    startCommand: python3 run.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
